# Generated by Django 4.2.7 on 2023-11-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_Model',
            new_name='Car',
        ),
    ]
