# Generated by Django 4.2.7 on 2023-11-29 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Brand must be more than 3 char')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='color must be more than 3 char'), django.core.validators.RegexValidator(message='Color accepts alphabets only', regex='^[a-zA-Z]+$')]),
        ),
    ]
