# Generated by Django 4.2.7 on 2023-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_rename_login_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(error_messages={'max_length': 'The name must be less than 50 char', 'required': 'Name is required'}, max_length=50),
        ),
    ]
