# Generated by Django 4.2.7 on 2023-11-29 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_register_email_alter_register_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Name must be more than 3 char'), django.core.validators.RegexValidator(message='Name accepts alphabets only', regex='^[a-zA-Z]+(\\s[a-zA-Z]+)?$')]),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='Password must be between 6 to 15 char')]),
        ),
    ]
